---
title: "Ecoli Genome Analysis"
author: "Marian L. Schmidt"
date: "October 12, 2015"
output: html_document
---

Here I'm working with the data carpentry ecoli genomes data set.  I found it at this website:  


```{r set seed, echo = TRUE, eval=TRUE}
set.seed(69131657)
```


Below I am importing the **ecoli data** from our data folder.
```{r Import Data, echo = TRUE, eval = TRUE}
metadata <- read.csv('data/Ecoli_metadata.csv') # reading in my data file into an object named metadata 
#View(metadata) #looking at the table within R 
#str()
#?str # get help on str 
#??str # all help pages with str in it
str(metadata) # looking at structure of data frame 
mean(metadata$genome_size) # calculating the mean 
```

```{r load packages, eval = TRUE}
#install.packages("ggplot2")
library("ggplot2")
#?library
```

```{r data exploration, echo = TRUE, eval = TRUE, fig.center = TRUE}
ggplot(metadata, aes(x = genome_size)) +
  geom_bar(stat = "bin", binwidth=0.01) # create a bar plot (histogram) with bins by a genome size of 0.01
```

Always include session info for reproducible documents!

```{r session info}
#install.packages("devtools")
#library(devtools)
devtools::session_info()
```


